services:
  - type: web
    name: david-ai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
  - type: static
    name: david-ai-frontend
    env: static
    buildCommand: echo 'Build complete'
    startCommand: python -m http.server 8000
    staticPublishPath: .
    autoDeploy: true
